### ISSUE TITLE
`CSFeeOracle` can be re-initilized

### ISSUE THREAD

**Issue by djanerch1** [shieldify-security/issues#14]
## Severity

Critical

## Description

Malicious user can re-initilize `CSFeeOracle` contract

## Impact

A malicious user can reinitialize the contract and appoint themselves as the admin. This would give them full control over the contract, including the ability to manage staked funds, alter configurations, and potentially disrupt or drain the staking system.

## Attack Scenario

1. A malicious user identifies the vulnerability in the `CSFeeOracle` contract.
2. The attacker calls the initialize function and sets their own address as the admin.
3. With administrative privileges, the attacker gains control over the contract, allowing him to set everything how he would like.

## Recommendations

Implement an Initialization Guard: Ensure the contract's initialize function can only be called once. This can be achieved by including a state variable that tracks whether initialization has occurred and a modifier to prevent re-initialization.

```javascript
bool private initialized = false;

modifier notInitialized() {
    require(!initialized, "Contract already initialized");
    _;
}

function initialize(address admin) public notInitialized {
    // Initialization logic here
    initialized = true;
}
```

**Comment by ShieldifyMartin** [comment]
Dup of #8
