### ISSUE TITLE
`AssetRecovererLib` lacks access control for functions

### ISSUE THREAD

**Issue by djanerch1** [shieldify-security/issues#15]
## Severity

High

## Description

The `AssetRecovererLib` library must include an `_onlyRecoverer` modifier for its functions to ensure proper access control.

## Impact

Currently, any user has access to the functions within this library.

## Attack Scenario

If a contract implementing `AssetRecovererLib` receives some Ether, an attacker could call the `recoverEther` function and withdraw all the Ether.

## Recommendations

Add the `_onlyRecoverer` modifier to the functions within the `AssetRecovererLib` library. This will prevent unauthorized users from calling these functions.

**Comment by Ptodoroff** [comment]
Please elaborate on all sections.

**Comment by djanerch1** [comment]
## Severity

High

## Description

The current implementation does not have a way to limit access, allowing people who shouldn't have access to use this function. This creates a serious security risk and can lead to misuse.

## Impact

Unauthorized users could take advantage of this vulnerability, causing problems with admin operations. This could result in the loss of unclaimed yield and disrupt how the system is supposed to work.

## Attack Scenario

1. Bob is admin, starts a transaction to claim ETH or ERC-20 tokens stored in a contract.
2. Alice sees Bob's transaction and performs a front-running attack, submitting her transaction before Bob's to take the unclaimed yield.
3. As a result, Bob gets 0 ETH or ERC-20 tokens because Alice's transaction goes through first, taking the yield meant for Bob.

## Location of Affected Code

AssetRecovererLib.sol

## Recommendation

Add an access control mechanism to limit this function to authorized users only. This will stop unauthorized access and make sure only those with the right permissions can perform important actions.

**Comment by ShieldifyMartin** [comment]
There is already an `_onlyRecoverer` access control on all of the contracts using the AssetRecoverer library (, src/CSAccounting.sol, CSFeeDistributor.sol, CSModule.sol).
