### ISSUE TITLE
Incorrect event parameter order in `CSAccounting::depositWstETH` 

### ISSUE THREAD

**Issue by 00xWizard** [shieldify-security/issues#43]
## Severity

Low

## Description

In the contract `CSAccounting`, the `depositWstETH` function calls the internal `_depositWstETH` function, which emits the event `BondDepositedWstETH`. However, the order of parameters in `CSAccounting:: CSBondCore._depositWstETH`  does not match the order defined in the event's declaration in the abstract contract `CSBondCore`. The correct order in the event declaration should be `uint256` `nodeOperatorId`, `address` `from`, and `uint256` `amount`. The current implementation incorrectly emits the parameters as `address` `from`, `uint256` `nodeOperatorId`, `uint256` `amount`.

CSBondCore.sol
```
 function _depositWstETH(
        address from,
        uint256 nodeOperatorId,
        uint256 amount
    ) internal {
     
 --------Rest of the Code--------


   emit BondDepositedWstETH(nodeOperatorId, from, amount);
    }
```

CSAccounting.sol

```
 function depositWstETH(
        address from,
        uint256 nodeOperatorId,
        uint256 wstETHAmount,
        PermitInput calldata permit
    ) external whenResumed onlyCSM {
   
------Rest of the Code------


        CSBondCore._depositWstETH(from, nodeOperatorId, wstETHAmount);
    }

```

## Impact

mismatch in the order of event parameters can cause incorrect data logging in the events. This discrepancy can lead to issues in data parsing and contracts that rely on the event logs, potentially resulting in incorrect interpretation of the logged data. It can also cause a compilation error, preventing the contract from being deployed or updated.

## Location of Affected Code
https://github.com/lidofinance/community-staking-module/blob/8ce9441dce1001c93d75d065f051013ad5908976/src/CSAccounting.sol#L245

## Recommendation

Ensure that the order of parameters in `CSAccounting` matches the order specified in the event declaration in CSBondCore. 

```
 CSBondCore._depositWstETH(nodeOperatorId, from, amount);

```

**Comment by ShieldifyMartin** [comment]
Would you be able to double-check as the event declaration is as follows:
```
event BondDepositedWstETH( uint256 indexed nodeOperatorId, address from, uint256 amount );
```
and from what I see the event is emitted exactly like this:
```
emit BondDepositedWstETH(nodeOperatorId, from, amount);
```
<img width="527" alt="image" src="https://github.com/user-attachments/assets/aafb5235-d003-4144-9848-253c0701522c">

**Comment by 00xWizard** [comment]
After having a firmer grip on the codebase, I just reviewed the event and the report, and I confirm that the event is emitted correctly, please mark the submission as closed
